#Must edit ~/.bashrc to reference this file for aliases

#	Overwriting basic commands
alias ls='ls -ph'
alias rm='rm -I'
alias temp='acpi -t'
alias tarballpack='tar cvzf $1 $2'
alias tarballunpack='tar xzvf'
alias maxbright='sudo setpci -s 00:02.0 f4.b=ff'
alias dwmcompile='cd ~/bin/dwm; makepkg -efi --skipinteg; cd -'
alias m='smplayer'
alias sus='sudo pm-suspend'
alias s='screen'
alias monitor-vga='xrandr --output LVDS1 --off --output VGA1 --auto'
alias monitor-eee='xrandr --output LVDS1 --auto --output VGA1 --off'
alias pandora='adobe-air /opt/pandora/pandora_2_0_2.air &'

#	Connecting to GT places
alias connectacme='ssh pjackson6@acme.gatech.edu'
alias retrieveacme='scp pjackson6@acme.gatech.edu:$1 $2'
alias retrievediracme='scp -r pjackson6@acme.gatech.edu:$1 $2'
alias transferacme='scp $1 pjackson6@acme.gatech.edu:$2'
alias transferdiracme='scp -r $1 pjackson6@acme.gatech.edu:$2'
alias connectece='ssh -Y pjackson6@ecelinsrv1.ece.gatech.edu'
alias retrieveece='scp pjackson6@ecelinsrv1.ece.gatech.edu:$1 $2'
alias retrievedirece='scp -r pjackson6@ecelinsrv1.ece.gatech.edu:$1 $2'
alias transferece='scp $1 pjackson6@ecelinsrv1.ece.gatech.edu:$2'
alias transferdirece='scp -r $1 pjackson6@ecelinsrv1.ece.gatech.edu:$2'

#	Publishing webpages to acme.gatech or localhost apache
#alias publish='scp -r ~/public_html pjackson6@acme.gatech.edu:; chmod o+x ~/public_html; chmod o+r ~/public_html/*'
#alias publish='sudo cp -r /home/patty/public_html/* /var/www/'
#alias publish1='sudo cp -r /home/patty/public_html/week1/* /var/www/week1/'
#alias publish2='sudo cp -r /home/patty/public_html/week2/* /var/www/week2/'
#alias publish3='sudo cp -r /home/patty/public_html/week3/* /var/www/week3/'
#alias publish4='sudo cp -r /home/patty/public_html/week4/* /var/www/week4/'
#alias publish5='sudo cp -r /home/patty/public_html/week5/* /var/www/week5/'

#	Upgrading with bauerbill & pacman
alias u='sudo bauerbill -Syu --rebase --aur --build-as patty'
alias i='sudo bauerbill -S --aur --build-as patty'
alias r='sudo pacman -Rs'
alias clean='rm -rf /tmp/bauerbill'
alias search='bauerbill -Ss --aur'

