#!/bin/bash


ide=$2
echo Creating links for $ide
exec<$1
if [ ! -h ~/workspace ]
then
	mkdir ~/workspace
fi
if [ ! -h ~/workspace/$2 ]
then
	mkdir ~/workspace/$2
fi
while read line
do
	if [ ! -h ~/workspace/$2/$line ]
	then
		mkdir ~/workspace/$2/$line
	fi
	if [ -d ~/bin/Projects/$line/inc -a ! -h ~/workspace/$2/$line/inc ]
	then
		ln -s ~/bin/Projects/$line/inc ~/workspace/$2/$line/inc
	fi
	if [ -d ~/bin/Projects/$line/src -a ! -h ~/workspace/$2/$line/src ]
	then
		ln -s ~/bin/Projects/$line/src ~/workspace/$2/$line/src
	fi
	if [ -d ~/bin/Projects/$line/data -a ! -h ~/workspace/$2/$line/data ]
	then
		ln -s ~/bin/Projects/$line/data ~/workspace/$2/$line/data
	fi
	if [ -d ~/bin/Projects/$line/ui -a ! -h ~/workspace/$2/$line/ui ]
	then
		ln -s ~/bin/Projects/$line/ui ~/workspace/$2/$line/ui
	fi
	echo $line
done
echo All Finished
