def Euler_29():
	'''
		For 2<=a,b<=100, how many unique terms are generated by a^b?
	'''
	ret = set()
	for a in range(2,101):
		ret |= set([a**b for b in range(2,101)])

	return len(ret)

if __name__ == '__main__':
	print(Euler_29())
