
# Check for an interactive session
[ -z "$PS1" ] && return

PS1='\[\033[1;32m\]\W/\[\033[0m\] '

#	Overwriting basic commands
alias ls='ls -ph'
alias rm='rm -I'
alias temp='acpi -t'
alias tarballpack='tar cvzf $1 $2'
alias tarballunpack='tar xzvf'
alias maxbright='sudo setpci -s 00:02.0 f4.b=ff'
alias dwmcompile='cd ~/bin/dwm; cp config.h src/config.h; makepkg -efi --skipinteg; cd -'
alias m='smplayer'
alias sus='sudo pm-suspend'
alias s='screen'
alias monitor-vga='xrandr --output LVDS1 --off --output VGA1 --auto'
alias monitor-eee='xrandr --output LVDS1 --auto --output VGA1 --off'
alias monitor-dual='xrandr --output LVDS1 --auto --output VGA1 --auto; xrandr --output VGA1 --right-of LVDS1'
alias vp='vim -u ~/.vimrc-p'
alias kindle='wine C:\\Program\ Files\ \(x86\)\\Amazon\\Kindle\ For\ PC\\KindleForPC.exe'

#	Upgrading with bauerbill & pacman
#alias u='sudo bauerbill -Syu --rebase --aur --build-as patty'
#alias i='sudo bauerbill -S --aur --build-as patty'
alias r='sudo pacman -Rs'
#alias clean='rm -rf /tmp/bauerbill'
#alias search='bauerbill -Ss --aur'

#   Upgrading with yaourt
alias u='yaourt -Syua'
alias i='yaourt -S'

