#ifndef PRIMES_H
#define PRIMES_H
#include <stdint.h>
#include <stdbool.h>

/*
 * Sieve of Eratosthenes
 *
 * Returns a pointer to an array that contains a Prime List in bitwise, wheel factorized form
 */
uint8_t* SieveEratosthenes(uint32_t);

/*
 * Prime List
 *
 * Returns a pointer to an array that contains a list of primes beginning at index 0 with 2
 * The last index+1 value is set to 0
 */
uint32_t* primeListE(uint32_t);
uint32_t* primeListE_inc(uint32_t, const uint8_t*);

/*
 * Next Prime
 *
 * Returns the next prime in the given SE list. Pass the SE list on the first call and use
 * NULL on the rest.  Passing any uns char array, including the original, after that results
 * in a restart of the count off. The ending value must be used each call.
 */
int NextPrime(int, const uint8_t*);

/*
 * Prime Index List
 *
 * Returns a pointer to a char array that defines primes by using the array index
 * Ex. Array[index]=1 if the index is prime
 */
uint8_t* primeIndexListE(int);
uint8_t* primeIndexListE_inc(int, const uint8_t*);

/*
 * Prime Factors
 *
 * Returns a pointer to an array of the prime factors of the input number
 * The input can be obtained by multiplying all the elements of the array
 */
int* primeFactorsE(int);
int* primeFactorsE_inc(int, const uint32_t*);
uint64_t* primeFactorsE_u64(uint64_t);

/*
 * Prime Check
 *
 * Returns true if the input is a prime
 * Takes in the Prime List generated by Sieve of Eratosthenes
 */
int isPrimeE(int, const uint8_t*);

/*
 * Prime Check
 *
 * Returns true if the input is a prime
 */
int isPrime(int);
int isPrime_u64(uint64_t);

#endif
